"""perf-add

Revision ID: 33ae8f98e530
Revises: 62d76412f2a0
Create Date: 2024-05-23 13:41:16.809846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ae8f98e530'
down_revision = '62d76412f2a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forwarder',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection', sa.String(length=20), nullable=False),
    sa.Column('activity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_forwarder_uid'), 'forwarder', ['uid'], unique=False)
    op.create_table('forwarder_perf',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_started', sa.DateTime(), nullable=True),
    sa.Column('search_ended', sa.DateTime(), nullable=True),
    sa.Column('update_started', sa.DateTime(), nullable=True),
    sa.Column('update_ended', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('order_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_uid'], ['orders.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_forwarder_perf_uid'), 'forwarder_perf', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forwarder_perf_uid'), table_name='forwarder_perf')
    op.drop_table('forwarder_perf')
    op.drop_index(op.f('ix_forwarder_uid'), table_name='forwarder')
    op.drop_table('forwarder')
    # ### end Alembic commands ###
